# Site settings
title:       Machine learning blog
author:      Sivaramakrishnan Sankarapandian
description: ":rocket: Blog for spreading knowledge about machine learning"
baseurl:     "" 
url:         "http://scelesticsiva.github.io" 

# Social Links
email:            scelesticsiva@gmail.com
github_username:  scelesticsiva
linkedin_username: siva2910

# Build settings
markdown: kramdown
permalink: pretty
